version: "3.9"

services:
  opentsdb:
    hostname: otsdb-host
    image: petergrace/opentsdb-docker:latest
    environment:
      - WAITSECS=30    
    ports:
      - 4242:4242
      - 60030:60030
    volumes:  
      - "./data:/data/hbase"
      - "./rollup_config.json:/etc/opentsdb/rollup_config.json"
      - "./opentsdb.conf:/etc/opentsdb/opentsdb.conf"
